export const INSTALL_BUILD = (packageName: string): string[] => {
  return [
    "#!/bin/bash",
    "",
    "### Use PKG_DIR as working directory.",
    "PKG_DIR=/tmp/_test_spk",
    "rm -rf $PKG_DIR",
    "mkdir -p $PKG_DIR",
    "",
    "### get spk packing functions",
    "source /pkgscripts/include/pkg_util.sh",
    "",
    "create_package_tgz() {",
    "\tlocal package_tgz_dir=/tmp/_package_tgz",
    "\tlocal binary_dir=$package_tgz_dir/usr/local/bin",
    "",
    "\t### clear destination directory",
    "\trm -rf $package_tgz_dir && mkdir -p $package_tgz_dir",
    "",
    "\t### install demo binary",
    "\tmkdir -p $binary_dir",
    "\t",
    `\t# 修正：/source/${packageName} → /source/${packageName}`,
    `\tif [ -f /source/${packageName}/demo ]; then`,
    `\t\tcp -av /source/${packageName}/demo $binary_dir/`,
    "\telse",
    '\t\techo "Error: demo binary not found!"',
    "\t\texit 1",
    "\tfi",
    "",
    "\t### create package.tgz",
    "\tpkg_make_package $package_tgz_dir \"${PKG_DIR}\"",
    "}",
    "",
    "create_spk(){",
    "\t# 生成 INFO 文件",
    `\t# 修正：/source/${packageName} → /source/${packageName}`,
    `\tif [ -f /source/${packageName}/INFO.sh ]; then`,
    `\t\tcd /source/${packageName}`,
    "\t\t./INFO.sh > INFO",
    "\t\tcd - > /dev/null  # 返回原目录",
    "\tfi",
    "\t",
    "\t# 复制文件",
    `\t# 修正：/source/${packageName} → /source/${packageName}`,
    `\t[ -d /source/${packageName}/scripts ] && cp -av /source/${packageName}/scripts $PKG_DIR/`,
    `\tls /source/${packageName}/PACKAGE_ICON*.PNG 2>/dev/null && cp -av /source/${packageName}/PACKAGE_ICON*.PNG $PKG_DIR`,
    `\t[ -d /source/${packageName}/conf ] && cp -av /source/${packageName}/conf $PKG_DIR/`,
    "\t",
    "\t# 复制 INFO",
    `\t# 修正：/source/${packageName} → /source/${packageName}`,
    `\tif [ -f /source/${packageName}/INFO ]; then`,
    `\t\tcp -av /source/${packageName}/INFO $PKG_DIR/`,
    `\telif [ -f /source/${packageName}/INFO.sh ]; then`,
    "\t\t# 如果没有 INFO 文件但有 INFO.sh，重新生成",
    `\t\t(cd /source/${packageName} && ./INFO.sh) > $PKG_DIR/INFO`,
    "\tfi",
    "",
    "\t### Create the final spk",
    "\tmkdir -p /image/packages",
    "\tpkg_make_spk ${PKG_DIR} \"/image/packages\" $(pkg_get_spk_family_name)",
    "}",
    "",
    "main() {",
    "\tcreate_package_tgz",
    "\tcreate_spk",
    "}",
    "",
    "main \"$@\""
  ];
};