/**
 * 代码/配置生成器
 * 根据用户配置生成 INFO、privilege、resource、scripts、模板文件
 */

import fs from 'fs';
import path from 'path';

// ─── INFO 文件────────────────────────────────────────────────────────────
export function generateINFO(cfg) {
  const lines = [
    '# INFO — Synology DSM 7 Package Metadata',
    '# Generated by synocat (https://github.com/your-org/synocat)',
    '# 字段文档: synopkg info <fieldname>',
    '',
    '# === 必填字段 ===',
    `package="${cfg.package}"`,
    `version="${cfg.version || '1.0.0-0001'}"`,
    `os_min_ver="${cfg.os_min_ver || '7.0-40000'}"`,
    `maintainer="${cfg.maintainer}"`,
  ];
  if (cfg.displayname) lines.push(`displayname="${cfg.displayname}"`);
  lines.push(`description="${cfg.description}"`);
  lines.push(`arch="${cfg.arch || 'noarch'}"`);
  if (cfg.maintainer_url) lines.push(`maintainer_url="${cfg.maintainer_url}"`);
  lines.push('');

  if (cfg.adminport || cfg.adminurl) {
    lines.push('# === 管理界面（三字段组合为访问链接）===');
    lines.push(`adminprotocol="${cfg.adminprotocol || 'http'}"`);
    lines.push(`adminport="${cfg.adminport}"`);
    lines.push(`adminurl="${cfg.adminurl || '/'}"`);
    lines.push('');
  }

  if (cfg.dsmuidir) {
    lines.push('# === DSM 桌面集成 ===');
    lines.push(`dsmuidir="${cfg.dsmuidir}"`);
    if (cfg.dsmappname) lines.push(`dsmappname="${cfg.dsmappname}"`);
    if (cfg.dsmapppage) lines.push(`dsmapppage="${cfg.dsmapppage}"`);
    lines.push('');
  }

  lines.push('# === 套件行为 ===');
  if (cfg.ctl_stop === 'no') lines.push('ctl_stop="no"');
  if (cfg.precheckstartstop) lines.push(`precheckstartstop="${cfg.precheckstartstop}"`);
  if (cfg.silent_install === 'yes') lines.push('silent_install="yes"');
  if (cfg.silent_upgrade === 'yes') lines.push('silent_upgrade="yes"');
  if (cfg.silent_uninstall === 'yes') lines.push('silent_uninstall="yes"');
  if (cfg.install_dep_packages) { lines.push(''); lines.push('# === 依赖 ==='); lines.push(`install_dep_packages="${cfg.install_dep_packages}"`); }
  return lines.join('\n') + '\n';
}

// ─── conf/privilege ───────────────────────────────────────────────────────
export function generatePrivilege() {
  return JSON.stringify({ defaults: { 'run-as': 'package' } }, null, 2) + '\n';
}

// ─── conf/resource ────────────────────────────────────────────────────────
export function generateResource(type, opts = {}) {
  const resource = {};
  const pkg = opts.package || 'mypkg';

  if (type === 'port') {
    resource['port-config'] = {
      protocol_type: 'both',
      ports: { main: { protocol: 'tcp', src: opts.port || 8080, dst: opts.port || 8080 } },
    };
  }
  if (type === 'data-share') {
    resource['data-share'] = {
      shares: [{ name: opts.shareName || `${pkg}-data`, permission: { rw: [`sc-${pkg}`] } }],
    };
  }
  if (type === 'mariadb') {
    resource['mariadb10-db'] = {
      'admin-account-m10': 'root',
      'admin-pw-m10': '{{WIZARD_MARIADB_ADMIN_PASSWORD}}',
      'create-db': { flag: true, 'db-name': `${pkg}_db`, 'db-collision': 'skip' },
      'grant-user': { flag: true, 'db-name': `${pkg}_db`, 'user-name': `${pkg}_user`, host: 'localhost', 'user-pw': '{{WIZARD_DB_PASSWORD}}' },
      'drop-db-uninst': false,
      'drop-user-uninst': false,
    };
  }
  if (type === 'docker') {
    resource['docker-project'] = {
      projects: [{ name: pkg, path: 'compose' }],
    };
  }
  if (type === 'port+share') {
    Object.assign(resource, generateResource('port', opts)['port-config'] ? { 'port-config': generateResource('port', opts)['port-config'] } : {});
    Object.assign(resource, { 'data-share': generateResource('data-share', opts)['data-share'] });
  }
  return JSON.stringify(resource, null, 2) + '\n';
}

// ─── start-stop-status 脚本──────────────────────────────────────────────
export function generateStartStopStatus(cfg = {}) {
  const pkg = cfg.package || 'mypkg';
  return `#!/bin/sh
# scripts/start-stop-status — 套件生命周期控制
# 文档: https://help.synology.com/developer-guide/synology_package/scripts.html
#
# 可用环境变量:
#   $SYNOPKG_PKGNAME       套件 ID
#   $SYNOPKG_PKGVER        套件版本
#   $SYNOPKG_PKGDEST       安装目录（如 /var/packages/${pkg}/target）
#   $SYNOPKG_PKGVAR        数据目录（/var/packages/${pkg}/var）
#   $SYNOPKG_TEMP_LOGFILE  写入此文件的内容会在操作完成后弹窗提示用户
#   $SYNOPKG_PKG_STATUS    当前操作类型：INSTALL / UPGRADE / UNINSTALL / START / STOP

PKG_BIN="$SYNOPKG_PKGDEST/bin/${pkg}"

case "$1" in
    start)
        # TODO: 启动您的服务
        # 示例（Node.js）: node "$SYNOPKG_PKGDEST/app/index.js" &
        # 示例（二进制）:   "$PKG_BIN" --daemon &
        echo "Starting ${pkg}..." > "$SYNOPKG_TEMP_LOGFILE"
        exit 0
        ;;

    stop)
        # TODO: 停止您的服务
        # 示例: kill \$(cat /var/run/${pkg}.pid)
        echo "Stopping ${pkg}..." > "$SYNOPKG_TEMP_LOGFILE"
        exit 0
        ;;

    status)
        # 返回码含义:
        #   0   运行中
        #   1   进程已死，/var/run pid 文件存在
        #   2   进程已死，/var/lock 锁文件存在
        #   3   未运行
        #   4   状态未知
        #   150 套件损坏，需重新安装
        # if pgrep -f "${pkg}" > /dev/null; then exit 0; fi
        exit 3
        ;;

    prestart)
        # 启动前检查（precheckstartstop=yes 时生效，DSM 7.0 开机时也会调用）
        # 返回非 0 会阻止启动
        exit 0
        ;;

    prestop)
        # 停止前检查（precheckstartstop=yes 时生效）
        exit 0
        ;;
esac

exit 0
`;
}

// ─── 其他脚本模板──────────────────────────────────────────────────────────
const SCRIPT_COMMENTS = {
  preinst:    '安装前检查。返回非 0 将中止安装，package.tgz 不会解压。',
  postinst:   '安装后初始化（如创建配置、初始化数据库）。返回非 0 将使套件进入 corrupted 状态。',
  preuninst:  '卸载前检查。返回非 0 将中止卸载。注意：不要在此脚本中制造副作用。',
  postuninst: '卸载后清理（如删除残留文件、清理数据库）。',
  preupgrade: '升级前检查（新版本脚本）。返回非 0 将中止升级。',
  postupgrade: '升级后初始化（新版本脚本）。返回非 0 将使套件进入 corrupted 状态。',
  prereplace: '替换前数据迁移（使用 install_replace_packages 时生效）。',
  postreplace: '替换后数据迁移。',
};

export function generateScript(name) {
  return `#!/bin/sh
# scripts/${name} — ${SCRIPT_COMMENTS[name] || name}
#
# 环境变量：
#   $SYNOPKG_PKGNAME, $SYNOPKG_PKGVER, $SYNOPKG_PKGDEST
#   $SYNOPKG_TEMP_LOGFILE  — 写入提示信息显示给用户
#   $SYNOPKG_DSM_LANGUAGE  — 用户界面语言（enu/chs/cht/jpn...）
#   $SYNOPKG_PKG_STATUS    — INSTALL / UPGRADE / UNINSTALL

exit 0
`;
}

// ─── ui/config (app.config) ───────────────────────────────────────────────
export function generateAppConfig(cfg = {}) {
  const { dsmappname = 'com.example.MyApp', displayname = 'My App' } = cfg;
  return JSON.stringify({
    [dsmappname]: {
      type: 'app',
      title: displayname,
      appWindow: dsmappname,
      allUsers: false,
      allowMultiInstance: false,
      hidden: false,
      icon: 'images/icon_{0}.png',
    },
  }, null, 2) + '\n';
}

// ─── JSON Schema for conf/resource ────────────────────────────────────────
export function generateResourceSchema() {
  return {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'Synology DSM 7 conf/resource',
    description: 'Resource worker configuration for Synology packages (DSM 7.2.2)',
    type: 'object',
    properties: {
      'data-share': {
        type: 'object',
        description: '申请共享文件夹访问权限',
        properties: {
          shares: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string', description: '共享文件夹名称' },
                permission: {
                  type: 'object',
                  properties: {
                    ro: { type: 'array', items: { type: 'string' }, description: '只读用户列表' },
                    rw: { type: 'array', items: { type: 'string' }, description: '读写用户列表' },
                  },
                },
              },
              required: ['name'],
            },
          },
        },
        required: ['shares'],
      },
      'port-config': {
        type: 'object',
        description: '防火墙端口注册',
        properties: {
          protocol_type: { type: 'string', enum: ['tcp', 'udp', 'both'] },
          ports: { type: 'object', additionalProperties: {
            type: 'object',
            properties: {
              protocol: { type: 'string', enum: ['tcp', 'udp'] },
              src: { type: 'integer' },
              dst: { type: 'integer' },
            },
          }},
        },
      },
      'docker-project': {
        type: 'object',
        description: 'Docker Compose 项目（需 ContainerManager >= 1432，DSM 7.2.1+）',
        properties: {
          'preload-image': { type: 'string', description: '预加载的镜像包路径' },
          projects: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                path: { type: 'string', description: '相对于 target 目录的 compose.yml 路径' },
                build_params: {
                  type: 'object',
                  properties: {
                    force_pull: { type: 'boolean', default: false },
                    force_recreate: { type: 'boolean', default: true },
                    build: { type: 'boolean', default: true },
                  },
                },
              },
              required: ['name', 'path'],
            },
          },
        },
        required: ['projects'],
      },
      'mariadb10-db': {
        type: 'object',
        description: 'MariaDB 10 数据库管理（需安装 MariaDB10 套件）',
        properties: {
          'admin-account-m10': { type: 'string' },
          'admin-pw-m10': { type: 'string' },
          'create-db': {
            type: 'object',
            properties: {
              flag: { type: 'boolean' },
              'db-name': { type: 'string' },
              'db-collision': { type: 'string', enum: ['replace', 'skip', 'error'] },
            },
          },
          'grant-user': {
            type: 'object',
            properties: {
              flag: { type: 'boolean' },
              'db-name': { type: 'string' },
              'user-name': { type: 'string' },
              host: { type: 'string' },
              'user-pw': { type: 'string' },
            },
          },
          'drop-db-uninst': { type: 'boolean' },
          'drop-user-uninst': { type: 'boolean' },
        },
        required: ['admin-account-m10'],
      },
    },
    additionalProperties: false,
  };
}

// ─── VSCode settings (JSON Schema 绑定) ────────────────────────────────────
export function generateVSCodeSettings() {
  return {
    'json.schemas': [
      {
        fileMatch: ['conf/resource'],
        schema: {
          $ref: '.synopkg/schemas/resource.schema.json',
        },
      },
      {
        fileMatch: ['conf/privilege'],
        schema: {
          $schema: 'http://json-schema.org/draft-07/schema#',
          type: 'object',
          required: ['defaults'],
          properties: {
            defaults: {
              type: 'object',
              required: ['run-as'],
              properties: {
                'run-as': { type: 'string', enum: ['package'], description: 'DSM 7.0 只支持 "package"，不再支持 "system"' },
              },
            },
          },
        },
      },
    ],
  };
}

// ─── 完整脚手架生成 ────────────────────────────────────────────────────────
export async function generateScaffold(targetDir, cfg) {
  const { templateType = 'minimal', hasUI, hasResource, resourceType, resourceOpts = {} } = cfg;
  const pkg = cfg.package;
  const files = [];

  const mkdirs = [
    targetDir, `${targetDir}/scripts`, `${targetDir}/conf`,
    `${targetDir}/.synopkg/schemas`, `${targetDir}/.vscode`,
  ];
  if (hasUI || templateType === 'vue-desktop')
    mkdirs.push(`${targetDir}/ui`, `${targetDir}/ui/images`, `${targetDir}/WIZARD_UIFILES`);
  if (templateType === 'node-service')
    mkdirs.push(`${targetDir}/src`);
  if (templateType === 'docker')
    mkdirs.push(`${targetDir}/compose`);

  mkdirs.forEach(d => fs.mkdirSync(d, { recursive: true }));

  // INFO
  fs.writeFileSync(`${targetDir}/INFO`, generateINFO(cfg)); files.push('INFO');

  // conf/privilege (必须)
  fs.writeFileSync(`${targetDir}/conf/privilege`, generatePrivilege()); files.push('conf/privilege');

  // conf/resource (可选)
  if (hasResource && resourceType && resourceType !== 'none') {
    fs.writeFileSync(`${targetDir}/conf/resource`, generateResource(resourceType, { package: pkg, ...resourceOpts }));
    files.push('conf/resource');
  }

  // scripts/
  const scripts = ['preinst','postinst','preuninst','postuninst','preupgrade','postupgrade'];
  for (const s of scripts) {
    const sp = `${targetDir}/scripts/${s}`;
    fs.writeFileSync(sp, generateScript(s));
    fs.chmodSync(sp, 0o755);
    files.push(`scripts/${s}`);
  }
  const sssp = `${targetDir}/scripts/start-stop-status`;
  fs.writeFileSync(sssp, generateStartStopStatus({ package: pkg }));
  fs.chmodSync(sssp, 0o755);
  files.push('scripts/start-stop-status');

  // JSON Schema (IDE 提示)
  fs.writeFileSync(`${targetDir}/.synopkg/schemas/resource.schema.json`,
    JSON.stringify(generateResourceSchema(), null, 2));
  files.push('.synopkg/schemas/resource.schema.json');

  // VSCode settings
  const vsSettings = `${targetDir}/.vscode/settings.json`;
  const existing = fs.existsSync(vsSettings) ? JSON.parse(fs.readFileSync(vsSettings, 'utf-8')) : {};
  const merged = { ...existing, ...generateVSCodeSettings() };
  fs.writeFileSync(vsSettings, JSON.stringify(merged, null, 2)); files.push('.vscode/settings.json');

  // 模板特定文件
  if (templateType === 'node-service') {
    generateNodeTemplate(targetDir, cfg);
    files.push('src/index.js', 'package.json');
  } else if (templateType === 'vue-desktop') {
    generateVueTemplate(targetDir, cfg);
    files.push('ui/config', 'ui/src/main.js', 'ui/package.json');
  } else if (templateType === 'docker') {
    generateDockerTemplate(targetDir, cfg);
    files.push('compose/compose.yml');
  }

  // 图标占位说明
  fs.writeFileSync(`${targetDir}/PACKAGE_ICON.README.md`,
    `# 图标文件\n\n请在此目录放置:\n- PACKAGE_ICON.PNG     64×64 像素（DSM 7.0 要求）\n- PACKAGE_ICON_256.PNG 256×256 像素（高分辨率）\n`);
  files.push('PACKAGE_ICON.README.md');

  // README
  fs.writeFileSync(`${targetDir}/README.md`, generateREADME(cfg, templateType));
  files.push('README.md');

  return files;
}

// ─── Node.js 模板 ─────────────────────────────────────────────────────────
function generateNodeTemplate(dir, cfg) {
  const pkg = cfg.package;
  fs.writeFileSync(`${dir}/src/index.js`,
`// ${pkg} — Main entry point
// DSM 环境变量可通过 process.env.SYNOPKG_PKGDEST 等访问

const port = parseInt(process.env.PORT || '${cfg.adminport || 8080}');

// TODO: 在此实现您的服务逻辑
console.log(\`[${pkg}] Server running on port \${port}\`);
`);

  const pkgJson = {
    name: pkg.toLowerCase(),
    version: cfg.version || '1.0.0',
    description: cfg.description,
    main: 'src/index.js',
    scripts: { start: 'node src/index.js', dev: 'node --watch src/index.js' },
    engines: { node: '>=18.0.0' },
  };
  fs.writeFileSync(`${dir}/package.json`, JSON.stringify(pkgJson, null, 2));
}

// ─── Vue 桌面应用模板──────────────────────────────────────────────────────
function generateVueTemplate(dir, cfg) {
  const appName = cfg.dsmappname || `com.example.${cfg.package}`;
  // ui/config (app.config)
  fs.writeFileSync(`${dir}/ui/config`, generateAppConfig({ dsmappname: appName, displayname: cfg.displayname || cfg.package }));

  // ui/src/
  fs.mkdirSync(`${dir}/ui/src`, { recursive: true });
  fs.writeFileSync(`${dir}/ui/src/main.js`,
`import Vue from 'vue';
import App from './App.vue';

SYNO.namespace('${appName}');

${appName}.Instance = Vue.extend({
  components: { App },
  template: '<App/>',
});
`);

  fs.writeFileSync(`${dir}/ui/package.json`, JSON.stringify({
    name: cfg.package.toLowerCase() + '-ui',
    version: '1.0.0',
    scripts: { build: 'webpack --mode production', dev: 'webpack --watch --mode development' },
    devDependencies: {
      '@babel/core': '7.18.6',
      'babel-loader': '8.0.6',
      'vue': '2.7.14',
      'vue-loader': '15.10.1',
      'vue-template-compiler': '2.7.14',
      'webpack': '5.91.0',
      'webpack-cli': '5.1.4',
    },
  }, null, 2));
}

// ─── Docker 模板──────────────────────────────────────────────────────────
function generateDockerTemplate(dir, cfg) {
  const port = cfg.adminport || 8080;
  fs.writeFileSync(`${dir}/compose/compose.yml`,
`# Docker Compose for ${cfg.package}
# DSM 会在安装/启动时自动管理此 Compose 项目
services:
  app:
    image: your-image:latest
    container_name: ${cfg.package}
    ports:
      - "${port}:${port}"
    restart: unless-stopped
    volumes:
      - app_data:/data
    environment:
      - NODE_ENV=production

volumes:
  app_data:
`);
}

// ─── README ──────────────────────────────────────────────────────────────
function generateREADME(cfg, templateType) {
  const templates = {
    minimal: '纯脚本套件（noarch）',
    'node-service': 'Node.js 后端服务',
    'vue-desktop': 'Vue.js 桌面应用',
    docker: 'Docker Compose 套件',
  };
  return `# ${cfg.displayname || cfg.package}

> ${cfg.description}

**模板类型**: ${templates[templateType] || templateType}  
**DSM 最低版本**: ${cfg.os_min_ver || '7.0-40000'}  
**维护者**: ${cfg.maintainer}

---

## 目录结构

\`\`\`
${cfg.package}/
├── INFO                       # 套件元数据（必须）
├── PACKAGE_ICON.PNG           # 64×64 图标（DSM 7.0 要求）
├── PACKAGE_ICON_256.PNG       # 256×256 高清图标
├── scripts/
│   ├── start-stop-status      # 生命周期控制（必须）
│   ├── preinst / postinst     # 安装前/后
│   ├── preuninst / postuninst # 卸载前/后
│   └── preupgrade / postupgrade # 升级前/后
├── conf/
│   ├── privilege              # 权限（DSM 7.0 强制必须）
│   └── resource               # 系统资源（可选）
├── .vscode/settings.json      # IDE JSON Schema 提示
└── .synopkg/schemas/          # JSON Schema 文件
\`\`\`

## 开发工作流

\`\`\`bash
# 1. 编辑业务代码和配置

# 2. 实时校验配置
synopkg validate .

# 3. 查看某个字段的文档
synopkg info adminport

# 4. 添加资源配置
synopkg add resource port
synopkg add resource data-share

# 5. 生成 .spk 打包结构
synopkg pack .

# 6. 用 Synology Toolkit 打包（需 Linux 环境）
# ./PkgCreate.py -v 7.2 -p [platform] ${cfg.package}
\`\`\`

## 关键说明（前端开发者须知）

### conf/privilege（必须！）
DSM 7.0 起强制要求，所有套件必须以普通用户权限运行：
\`\`\`json
{ "defaults": { "run-as": "package" } }
\`\`\`

### scripts/start-stop-status
DSM 通过此脚本控制套件生命周期，必须处理 \`start\`、\`stop\`、\`status\` 三个参数。

### package.tgz
套件的实际应用文件（可执行文件、UI 文件等）需打包到 \`package.tgz\`，  
解压后路径为 \`/var/packages/${cfg.package}/target/\`。

## 参考文档

- [DSM Developer Guide 7.2.2](https://help.synology.com/developer-guide/)
- [ExamplePackages](https://github.com/SynologyOpenSource/ExamplePackages)
- [pkgscripts-ng](https://github.com/SynologyOpenSource/pkgscripts-ng)
`;
}
