import type { ScaffoldConfig } from '../../types';

/**
 * Pure function — no file I/O, no side-effects.
 * Returns the full contents of an INFO file as a string.
 */
export function generateINFO(cfg: ScaffoldConfig): string {
  const lines: string[] = [
    '# INFO — Synology DSM 7 Package Metadata',
    '# Generated by synocat (https://github.com/synocatjs/synocat)',
    '# Field docs: synocat info <fieldname>',
    '',
    '# === Required fields ===',
    `package="${cfg.package}"`,
    `version="${cfg.version}"`,
    `os_min_ver="${cfg.os_min_ver}"`,
    `maintainer="${cfg.maintainer}"`,
    `description="${cfg.description}"`,
    `arch="${cfg.arch}"`,
    '',
  ];

  if (cfg.displayname)    lines.push(`displayname="${cfg.displayname}"`);
  if (cfg.maintainer_url) lines.push(`maintainer_url="${cfg.maintainer_url}"`);
  if (cfg.displayname || cfg.maintainer_url) lines.push('');

  if (cfg.adminport ?? cfg.adminurl) {
    lines.push('# === Admin UI (all three form the access link) ===');
    lines.push(`adminprotocol="${cfg.adminprotocol ?? 'http'}"`);
    lines.push(`adminport="${cfg.adminport ?? ''}"`);
    lines.push(`adminurl="${cfg.adminurl ?? '/'}"`);
    lines.push('');
  }

  if (cfg.dsmuidir) {
    lines.push('# === DSM Desktop integration ===');
    lines.push(`dsmuidir="${cfg.dsmuidir}"`);
    if (cfg.dsmappname) lines.push(`dsmappname="${cfg.dsmappname}"`);
    if (cfg.dsmapppage) lines.push(`dsmapppage="${cfg.dsmapppage}"`);
    lines.push('');
  }

  lines.push('# === Package behaviour ===');
  if (cfg.ctl_stop === 'no')          lines.push('ctl_stop="no"');
  if (cfg.precheckstartstop)          lines.push(`precheckstartstop="${cfg.precheckstartstop}"`);
  if (cfg.silent_install === 'yes')   lines.push('silent_install="yes"');
  if (cfg.silent_upgrade === 'yes')   lines.push('silent_upgrade="yes"');
  if (cfg.silent_uninstall === 'yes') lines.push('silent_uninstall="yes"');

  if (cfg.install_dep_packages) {
    lines.push('', '# === Dependencies ===');
    lines.push(`install_dep_packages="${cfg.install_dep_packages}"`);
  }

  return lines.join('\n') + '\n';
}